# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1097, 668)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.top_frame = QtWidgets.QFrame(self.widget)
        self.top_frame.setStyleSheet("border-radius: 7px;\n"
"font: 75 13pt \"微软雅黑\";")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.pushButton_4 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 10, 101, 41))
        self.pushButton_4.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 10, 101, 41))
        self.pushButton_5.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 10, 101, 41))
        self.pushButton_6.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 10, 101, 41))
        self.pushButton_7.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_8.setGeometry(QtCore.QRect(440, 10, 101, 41))
        self.pushButton_8.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_11.setGeometry(QtCore.QRect(550, 10, 101, 41))
        self.pushButton_11.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_10 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_10.setGeometry(QtCore.QRect(660, 10, 101, 41))
        self.pushButton_10.setStyleSheet("font: 75 15pt \"微软雅黑\";")
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout.addWidget(self.top_frame)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.time_lab = QtWidgets.QLabel(self.frame_2)
        self.time_lab.setGeometry(QtCore.QRect(0, 46, 91, 20))
        self.time_lab.setText("")
        self.time_lab.setObjectName("time_lab")
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 9)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.widget_2)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_welcome_lab = QtWidgets.QLabel(self.frame_3)
        self.top_welcome_lab.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.top_welcome_lab.setText("")
        self.top_welcome_lab.setObjectName("top_welcome_lab")
        self.verticalLayout_2.addWidget(self.top_welcome_lab)
        self.main_fram = QtWidgets.QFrame(self.frame_3)
        self.main_fram.setStyleSheet("")
        self.main_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_fram.setObjectName("main_fram")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.main_fram)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.opeartor_fram = QtWidgets.QFrame(self.main_fram)
        self.opeartor_fram.setStyleSheet("")
        self.opeartor_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.opeartor_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opeartor_fram.setObjectName("opeartor_fram")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.opeartor_fram)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.opeartor_fram)
        self.pushButton.setStyleSheet("border-radius: 7px;\n"
"font: 75 13pt \"微软雅黑\";")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.opeartor_fram)
        self.pushButton_2.setStyleSheet("border-radius: 7px;\n"
"font: 75 13pt \"微软雅黑\";")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.opeartor_fram)
        self.pushButton_3.setStyleSheet("border-radius: 7px;\n"
"font: 75 13pt \"微软雅黑\";")
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.relash_btn = QtWidgets.QPushButton(self.opeartor_fram)
        self.relash_btn.setStyleSheet("border-radius: 7px;\n"
"font: 75 13pt \"微软雅黑\";")
        self.relash_btn.setFlat(True)
        self.relash_btn.setObjectName("relash_btn")
        self.horizontalLayout_3.addWidget(self.relash_btn)
        self.verticalLayout_4.addWidget(self.opeartor_fram)
        self.cash1_lab = QtWidgets.QLabel(self.main_fram)
        self.cash1_lab.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.cash1_lab.setText("")
        self.cash1_lab.setObjectName("cash1_lab")
        self.verticalLayout_4.addWidget(self.cash1_lab)
        self.cash2_lab = QtWidgets.QLabel(self.main_fram)
        self.cash2_lab.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.cash2_lab.setText("")
        self.cash2_lab.setObjectName("cash2_lab")
        self.verticalLayout_4.addWidget(self.cash2_lab)
        self.cash3_lab = QtWidgets.QLabel(self.main_fram)
        self.cash3_lab.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.cash3_lab.setText("")
        self.cash3_lab.setObjectName("cash3_lab")
        self.verticalLayout_4.addWidget(self.cash3_lab)
        self.cash4_lab = QtWidgets.QLabel(self.main_fram)
        self.cash4_lab.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.cash4_lab.setText("")
        self.cash4_lab.setObjectName("cash4_lab")
        self.verticalLayout_4.addWidget(self.cash4_lab)
        self.cash5_lab = QtWidgets.QLabel(self.main_fram)
        self.cash5_lab.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.cash5_lab.setText("")
        self.cash5_lab.setObjectName("cash5_lab")
        self.verticalLayout_4.addWidget(self.cash5_lab)
        self.cash6_lab = QtWidgets.QLabel(self.main_fram)
        self.cash6_lab.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.cash6_lab.setText("")
        self.cash6_lab.setObjectName("cash6_lab")
        self.verticalLayout_4.addWidget(self.cash6_lab)
        self.cash7_lab = QtWidgets.QLabel(self.main_fram)
        self.cash7_lab.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.cash7_lab.setText("")
        self.cash7_lab.setObjectName("cash7_lab")
        self.verticalLayout_4.addWidget(self.cash7_lab)
        self.verticalLayout_2.addWidget(self.main_fram)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 7)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.widget_2)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMinimumSize(QtCore.QSize(100, 37))
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout.setContentsMargins(37, 33, 7, 7)
        self.formLayout.setHorizontalSpacing(7)
        self.formLayout.setVerticalSpacing(33)
        self.formLayout.setObjectName("formLayout")
        self.guihua_cb = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guihua_cb.sizePolicy().hasHeightForWidth())
        self.guihua_cb.setSizePolicy(sizePolicy)
        self.guihua_cb.setMinimumSize(QtCore.QSize(137, 37))
        self.guihua_cb.setMaximumSize(QtCore.QSize(137, 37))
        self.guihua_cb.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.guihua_cb.setObjectName("guihua_cb")
        self.guihua_cb.addItem("")
        self.guihua_cb.addItem("")
        self.guihua_cb.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.guihua_cb)
        self.canpin_cb = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canpin_cb.sizePolicy().hasHeightForWidth())
        self.canpin_cb.setSizePolicy(sizePolicy)
        self.canpin_cb.setMinimumSize(QtCore.QSize(137, 37))
        self.canpin_cb.setMaximumSize(QtCore.QSize(137, 37))
        self.canpin_cb.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.canpin_cb.setObjectName("canpin_cb")
        self.canpin_cb.addItem("")
        self.canpin_cb.addItem("")
        self.canpin_cb.addItem("")
        self.canpin_cb.addItem("")
        self.canpin_cb.addItem("")
        self.canpin_cb.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.canpin_cb)
        self.tools_cb = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_cb.sizePolicy().hasHeightForWidth())
        self.tools_cb.setSizePolicy(sizePolicy)
        self.tools_cb.setMinimumSize(QtCore.QSize(137, 37))
        self.tools_cb.setMaximumSize(QtCore.QSize(137, 37))
        self.tools_cb.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.tools_cb.setObjectName("tools_cb")
        self.tools_cb.addItem("")
        self.tools_cb.addItem("")
        self.tools_cb.addItem("")
        self.tools_cb.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.tools_cb)
        self.remind_cb = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remind_cb.sizePolicy().hasHeightForWidth())
        self.remind_cb.setSizePolicy(sizePolicy)
        self.remind_cb.setMinimumSize(QtCore.QSize(137, 37))
        self.remind_cb.setMaximumSize(QtCore.QSize(137, 37))
        self.remind_cb.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.remind_cb.setObjectName("remind_cb")
        self.remind_cb.addItem("")
        self.remind_cb.addItem("")
        self.remind_cb.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.remind_cb)
        self.my_account_cb = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.my_account_cb.sizePolicy().hasHeightForWidth())
        self.my_account_cb.setSizePolicy(sizePolicy)
        self.my_account_cb.setMinimumSize(QtCore.QSize(137, 37))
        self.my_account_cb.setMaximumSize(QtCore.QSize(137, 37))
        self.my_account_cb.setStyleSheet("font: 75 13pt \"微软雅黑\";")
        self.my_account_cb.setObjectName("my_account_cb")
        self.my_account_cb.addItem("")
        self.my_account_cb.addItem("")
        self.my_account_cb.addItem("")
        self.my_account_cb.addItem("")
        self.my_account_cb.addItem("")
        self.my_account_cb.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.my_account_cb)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.welcome_lab = QtWidgets.QLabel(self.frame)
        self.welcome_lab.setGeometry(QtCore.QRect(63, 29, 111, 31))
        self.welcome_lab.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.welcome_lab.setObjectName("welcome_lab")
        self.Person_info_lab = QtWidgets.QLabel(self.frame)
        self.Person_info_lab.setGeometry(QtCore.QRect(30, 90, 171, 41))
        self.Person_info_lab.setStyleSheet("font: 75 18pt \"微软雅黑\";")
        self.Person_info_lab.setText("")
        self.Person_info_lab.setObjectName("Person_info_lab")
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_3.setStretch(0, 7)
        self.verticalLayout_3.setStretch(1, 3)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_2.setStretch(0, 8)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)

        self.retranslateUi(Form)
        self.pushButton_4.clicked.connect(Form.cash_btn)
        self.pushButton_5.clicked.connect(Form.cunkuan_btn)
        self.pushButton_6.clicked.connect(Form.touzi_btn)
        self.pushButton_7.clicked.connect(Form.loan_btn)
        self.pushButton_8.clicked.connect(Form.zonghe_btn)
        self.pushButton_11.clicked.connect(Form.import_btn)
        self.pushButton_10.clicked.connect(Form.zixun_btn)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_4.setText(_translate("Form", "现   金"))
        self.pushButton_5.setText(_translate("Form", "存   款"))
        self.pushButton_6.setText(_translate("Form", "投   资"))
        self.pushButton_7.setText(_translate("Form", "借   贷"))
        self.pushButton_8.setText(_translate("Form", "综合分析"))
        self.pushButton_11.setText(_translate("Form", "重要事件"))
        self.pushButton_10.setText(_translate("Form", "股市资讯"))
        self.pushButton.setText(_translate("Form", "添加"))
        self.pushButton_2.setText(_translate("Form", "修改"))
        self.pushButton_3.setText(_translate("Form", "删除"))
        self.relash_btn.setText(_translate("Form", "刷新"))
        self.guihua_cb.setItemText(0, _translate("Form", "理 财 规 划"))
        self.guihua_cb.setItemText(1, _translate("Form", "理财规划案例"))
        self.guihua_cb.setItemText(2, _translate("Form", "理财规划交流"))
        self.canpin_cb.setItemText(0, _translate("Form", "理 财 产 品"))
        self.canpin_cb.setItemText(1, _translate("Form", "银行本币理财"))
        self.canpin_cb.setItemText(2, _translate("Form", "银行外币理财"))
        self.canpin_cb.setItemText(3, _translate("Form", "人寿保险"))
        self.canpin_cb.setItemText(4, _translate("Form", "财产保险"))
        self.canpin_cb.setItemText(5, _translate("Form", "基金公司查询"))
        self.tools_cb.setItemText(0, _translate("Form", "理 财 工 具"))
        self.tools_cb.setItemText(1, _translate("Form", "理财计算器"))
        self.tools_cb.setItemText(2, _translate("Form", "生活工具"))
        self.tools_cb.setItemText(3, _translate("Form", "理财网站导航"))
        self.remind_cb.setItemText(0, _translate("Form", "日 程 提 醒"))
        self.remind_cb.setItemText(1, _translate("Form", "重要事件       "))
        self.remind_cb.setItemText(2, _translate("Form", "重点资讯"))
        self.my_account_cb.setItemText(0, _translate("Form", "我 的 账 户"))
        self.my_account_cb.setItemText(1, _translate("Form", "现金"))
        self.my_account_cb.setItemText(2, _translate("Form", "存款"))
        self.my_account_cb.setItemText(3, _translate("Form", "投资"))
        self.my_account_cb.setItemText(4, _translate("Form", "借贷"))
        self.my_account_cb.setItemText(5, _translate("Form", "综合分析        "))
        self.welcome_lab.setText(_translate("Form", "欢迎您 :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
